# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Je2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Je2
pod 'AlamofireImage', '~> 3.5'


  target 'Je2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Je2UITests' do
    # Pods for testing
  end

end
